spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/beatbuddy
    username: lee
    password:
    driver-class-name: org.mariadb.jdbc.Driver

spotify:
  client-id: b2b9f759d8c04cf694064e87774ffa2b
  client-secret: f49d7c7b20c04b4bba9c7248e4a38c87

jwt:
  secret: beatbuddy-jwt-secret-key-must-be-32chars-min
